name: Master Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven Build
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin] prepare release')"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: sonatype-nexus-snapshots
          server-username: NEXUS_OSS_USERNAME
          server-password: NEXUS_OSS_PASSWORD
      - name: Maven Build
        run: mvn verify sonar:sonar deploy -Pcoverage -Dsonar.organization=jaxxy-rs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NEXUS_OSS_USERNAME: ${{ secrets.NEXUS_OSS_USERNAME }}
          NEXUS_OSS_PASSWORD: ${{ secrets.NEXUS_OSS_PASSWORD }}